#!/bin/bash

# Make sure the necessary environment variables are set.
if [ -z "$NGINX_SERVER_NAME" ]; then NGINX_SERVER_NAME=localhost; fi
if [ -z "$NGINX_PORT" ]; then NGINX_PORT=80; fi

# Try set custom settings.
cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
sed -e "s/^\s*server_name\s*localhost;$/server_name  $NGINX_SERVER_NAME;/" \
    -e "s/^\s*listen\s*[0-9]*;$/listen       $NGINX_PORT;/" \
    -e "/^\s*index\s*index\.html\s*index\.htm;$/a try_files \$uri \$uri\/ \/index.html;" \
    < /etc/nginx/conf.d/default.conf.orig > /etc/nginx/conf.d/default.conf

# Start Nginx.
/usr/sbin/nginx
